version: '3.8'

services:
  db:
    container_name: postgresdb
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./postgres/:/var/lib/posgresql/data
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
